version: '3.1'
services:
  mysql-ms1:
    image: mysql:8.0
    container_name: container_mysql-ms1
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ms1_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user
    ports:
      - '3306:3306'
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD

  phpmyadmin-ms1:
    container_name: container_phpmyadmin-ms1
    image: phpmyadmin/phpmyadmin
    ports:
      - '8085:80'
    environment:
      MYSQL_ROOT_PASSWORD: root
      PMA_HOST: mysql-ms1
      PMA_USER: user
      PMA_PASSWORD: user
    depends_on:
      - mysql-ms1
    restart: unless-stopped
volumes:
  mysql_data:
    driver: local

